site_name: ArtPlace
site_author: Berserk
site_description: >-
  Git pages voltado para documentar o projeto ArtPlace da disciplina de
  Requisitos de Software na Universidade de Brasília

site_url: https://mdsreq-fga-unb.github.io/2023.2-ArtPalce/

theme:
  name: material
  logo: assets/logoUniBuddy.png
  favicon: assets/brasao.png
  icon: 
    repo: fontawesome/brands/github
  language: pt-BR
  palette: 
    - scheme: default
      primary: red
      accent: light red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: red
      accent: light red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


nav:
  - Página Inicial: index.md
  - História: historia.md
  - Visão geral do produto: produto.md
  - Visão geral do projeto: projeto.md
  - Processo de desenvolvimento: processo.md
  - Lições aprendidas: licoes.md

markdown_extensions:
  - tables
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
