site_name: ArtPlace
site_author: Berserk
site_description: >-
  Git pages voltado para documentar o projeto ArtPlace da disciplina de
  Requisitos de Software na Universidade de Brasília

site_url: https://mdsreq-fga-unb.github.io/2023.2-ArtPlace/



theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: red
      accent: black
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: red
      accent: black
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Página Inicial: index.md
  - História: historia.md
  - Documentação:
    - Visão geral do produto: produto.md
    - Ciclos: 
      - Ciclo 1: Ciclos/ciclo1.md
      - Ciclo 2: Ciclos/ciclo2.md
      - Ciclo 3: Ciclos/ciclo3.md
      - Ciclo 4: Ciclos/ciclo4.md
      - Ciclo 5: Ciclos/ciclo5.md
      - Ciclo 6: Ciclos/ciclo6.md
      - Ciclo 7: Ciclos/ciclo7.md
      - Ciclo 8: Ciclos/ciclo8.md
      - Ciclo 9: Ciclos/ciclo9.md
  - Missão 1: 
    - Visão geral do projeto: projeto.md
    - Processo de desenvolvimento: processo.md
  - Missão 2: 
    - SAFe: SAFe.md
    - Backlog: Backlog.md
    - MVP: MVP.md 
    - Avaliação da Facção Gunthers: verificacao_e_validacao_gunthers.md
  - Lições aprendidas: licoes.md

markdown_extensions:
  - tables
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

